---
# Source: go-demo-8/charts/go-demo-8-db/templates/svc-standalone.yaml

apiVersion: v1
kind: Service
metadata:
  name: go-demo-8-db
  labels:
    app: go-demo-8-db
    chart: go-demo-8-db-5.3.0
    release: "go-demo-8"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: go-demo-8-db
    release: "go-demo-8"
